require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'WinnerWish' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  pod 'tipsi-stripe', :path => '../node_modules/tipsi-stripe'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'
  pod 'Stripe', '~> 19.0.1'
  target 'WinnerWishTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'WinnerWish-tvOS' do
  # Pods for WinnerWish-tvOS

  target 'WinnerWish-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
