import {StyleSheet, Dimensions} from 'react-native';
import {Colors} from 'react-native/Libraries/NewAppScreen';
// import theme from '../../../theme/colors';
const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    // backgroundColor: 'white',
    // justifyContent: 'center',
    // alignItems: 'center',
  },
  button: {
    backgroundColor: 'white',

    elevation: 10,
    paddingHorizontal: 15,
    paddingVertical: 10,
    width: '50%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  largeText: {
    fontSize: 16,
    fontWeight: '300',
    marginLeft: 10,
  },
  mediumText: {
    fontSize: 13,
  },
  activityIndicatorStyle: {
    flex: 1,
    position: 'absolute',
    marginLeft: 'auto',
    marginRight: 'auto',
    marginTop: 'auto',
    marginBottom: 'auto',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
  },
  backArrow: {
    height: 25,
    width: 25,

    borderRadius: 50,
    marginLeft: 30,
    // backgroundColor: theme.colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  input: {
    margin: 10,
    // backgroundColor: 'skyblue',
    padding: 15,
    borderRadius: 5,
    width: '95%',
    fontFamily: 'geometriaBold',
    alignSelf: 'center',
    textAlign: 'center',
    // justifyContent:'center',
    // alignItems:'center'
  },
  fieldContainer: {
    paddingVertical: 5,
    flex: 0.8,
  },
  buttonStyle: {
    marginTop: '5%',
    // padding: 5,
    backgroundColor: colors.primary,
    height: 50,
    borderRadius: 100,
    width: '60%',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    borderWidth: 0.2,
    borderColor: 'gray',
    marginBottom: 10,
  },
  wrapper: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  slide1: {
    flex: 0.8,
    height: '70%',
    width: '70%',
    marginTop: '20%',
    // justifyContent: 'center',
    alignSelf: 'center',
    // alignItems: 'center',
    // textAlign: 'center',
    backgroundColor: 'white',
    elevation: 3,
    shadowOffset: {height: 0.6, width: 2},
    shadowColor: 'blue',
  },
  slide2: {
    flex: 0.8,
    height: '70%',
    width: '70%',
    marginTop: '20%',
    // justifyContent: 'center',
    // alignSelf: 'center',
    // alignItems: 'center',
    textAlign: 'justify',
    backgroundColor: '#9DD6EB',
  },
  slide3: {
    flex: 0.8,
    height: '70%',
    width: '70%',
    marginTop: '20%',
    justifyContent: 'center',
    alignSelf: 'center',
    alignItems: 'center',
    // textAlign: 'center',
    backgroundColor: '#9DD6EB',
  },
  text: {
    color: 'red',
    fontSize: 30,
    fontWeight: 'bold',
  },
});
export default styles;
