import {StyleSheet} from 'react-native';
import colors from '../../../theme/colors';
import {Fonts} from '../../../utils/Fonts';
const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: 'white',
  },
  medium: {fontFamily: Fonts.PoppinsMedium, fontSize: 15},
  large: {fontFamily: Fonts.PoppinsMedium, fontSize: 16},
  logo: {
    height: 50,
    width: 50,
    resizeMode: 'contain',
    alignSelf: 'center',
    resizeMode: 'contain',
  },
  text: {
    justifyContent: 'center',
    alignContent: 'center',
    alignSelf: 'center',
    fontSize: 16,
    fontWeight: 'bold',
    alignItems: 'center',
    alignItems: 'center',
  },
  cardContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',

    marginVertical: 10,
    marginHorizontal: 15,
    padding: 15,
    borderRadius: 2,
    backgroundColor: '#fff',
    borderRadius: 5,
    elevation: 5,
    shadowColor: '#BDBDBD',
    shadowOffset: {
      width: 0,
      height: 1,
    },
  },
  textstyle: {
    justifyContent: 'center',
    alignItems: 'center',
    // backgroundColor: 'red',
    alignContent: 'center',
    height: 150,
    marginTop: 10,
  },

  inputText: {
    margin: 10,
    padding: 10,
    paddingHorizontal: 20,
    textAlign: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F8FEFF',
    fontFamily: Fonts.PoppinsMedium,
    elevation: 5,
    borderColor: colors.primary,
    color: 'gray',
    shadowColor: '#BDBDBD',
    shadowOffset: {
      width: 0,
      height: 1,
    },
  },
  button: {
    backgroundColor: 'red',
    position: 'absolute',
    bottom: 20,
    elevation: 10,
    paddingHorizontal: 15,
    paddingVertical: 10,
    width: '50%',
    height: '5%',
  },
  medium: {
    fontSize: 14,
    fontFamily: Fonts.PoppinsMedium,
    textAlign: 'center',
  },
  mediumx: {
    fontFamily: Fonts.PoppinsMedium,
    fontSize: 20,
    // position: 'absolute',
    // bottom: 0,
    marginTop: 5,
    // justifyContent: 'center',
    // alignContent: 'center',
    // alignSelf: 'center',
    // alignItems: 'center',
    // backgroundColor: 'red',
    backgroundColor: colors.secondary,
    textAlign: 'center',
    height: 40,
    // flex: 0.1,
    color: 'white',
    width: '90%',
  },
});
export default styles;
